[package]
name = "developing_stories"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.4.1"
bevy = "0.17.3"
bevy-tnua-avian3d = "0.8.0"
bevy_common_assets = { version = "0.14.0", features = ["ron"] }
serde = { version = "1.0.228", features = ["derive"] }
